using Bussiness.Concrate;
using DataAccess.EntityFramework;
using Entities.Concrate;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;

namespace FormUI
{
    public partial class AdminPage : Form
    {
        public AdminPage()
        {
            InitializeComponent();
            employeeqlLoad();
            adminSqlLoad();

        }

        AdminManager adminManager = new  AdminManager(new EfAdminDal(),new EfEmployeeDal());
        private void simpleButton1_Click(object sender, EventArgs e)//ADD EMPLOYEE
        {
          var result= adminManager.AddEmployee(new Employee{ name=textEdit1
           .Text,surname=textEdit2.Text,password=textEdit3.Text});
            MessageBox.Show(result.Message);
            employeeqlLoad();

        }

        private void simpleButton2_Click(object sender, EventArgs e)//DELETE EMPLOYEE
        {
          var result=  adminManager.DeleteEmployee((new Employee
            {
                Id=Convert.ToInt32(textEdit7.Text),
                name = textEdit1
           .Text,
                surname = textEdit2.Text,
                password = textEdit3.Text
            }));
            MessageBox.Show(result.Message);
            employeeqlLoad();
        }

        private void simpleButton3_Click(object sender, EventArgs e)//UPDATE EMPLOYEE
        {
         var result=   adminManager.UpdateEmployee((new Employee
            {
                Id = Convert.ToInt32(textEdit7.Text),
                name = textEdit1
           .Text,
                surname = textEdit2.Text,
                password = textEdit3.Text
            }));
            MessageBox.Show(result.Message);
            employeeqlLoad();

        }

        private void simpleButton6_Click(object sender, EventArgs e)//ADMİN EKLE
        {
          var result =   adminManager.Add(new Admins { Name = textEdit4.Text, Surname = textEdit5.Text, Password = textEdit6.Text });
            MessageBox.Show(result.Message);
            adminSqlLoad();
        }

        private void simpleButton5_Click(object sender, EventArgs e)//ADMİN SİL
        {
           var result= adminManager.Delete(new Admins { Name = textEdit4.Text, Surname = textEdit5.Text, Password = textEdit6.Text ,Id=Convert.ToInt32(textEdit8.Text)});
            MessageBox.Show(result.Message);
            adminSqlLoad();

        }

        private void simpleButton4_Click(object sender, EventArgs e)//ADMİN GÜNCELLE
        {
          var result=  adminManager.Update(new Admins { Name = textEdit4.Text, Surname = textEdit5.Text, Password = textEdit6.Text, Id = Convert.ToInt32(textEdit8.Text) });
            MessageBox.Show(result.Message);
            adminSqlLoad();

        }
        private void adminSqlLoad()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DataAccess.EntityFramework.BarkodYazıcıContext dbContext = new DataAccess.EntityFramework.BarkodYazıcıContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Admins.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.Admins.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
        }
        private void employeeqlLoad()
        {
            DataAccess.EntityFramework.BarkodYazıcıContext dbContext1 = new DataAccess.EntityFramework.BarkodYazıcıContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext1.Employee.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl2.DataSource = dbContext1.Employee.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
    }

